"""initial schema

Revision ID: c7315b44fd5d
Revises: 
Create Date: 2026-07-24 13:23:11.222597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'c7315b44fd5d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enable pgvector extension
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False, comment='Название книги / фанфика'),
    sa.Column('chunk_index', sa.Integer(), nullable=False, comment='Номер чанка в документе'),
    sa.Column('content', sa.Text(), nullable=False, comment='Текст чанка'),
    sa.Column('embedding', Vector(dim=1536), nullable=False, comment='Эмбединг (размерность зависит от модели)'),
    sa.Column('extra_meta', sa.JSON(), nullable=False, comment='Дополнительные метаданные'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_document_chunks_embedding', 'document_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('idx_document_chunks_source', 'document_chunks', ['source'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_chat_id', sa.Integer(), nullable=False, comment='Telegram chat_id'),
    sa.Column('balance', sa.Integer(), nullable=False, comment='Талоны'),
    sa.Column('trial_messages_left', sa.Integer(), nullable=False, comment='Бесплатные сообщения (триал)'),
    sa.Column('is_admin', sa.Boolean(), nullable=False, comment='Администратор'),
    sa.Column('is_allowed', sa.Boolean(), nullable=False, comment='Разрешено ли пользоваться ботом'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_chat_id')
    )
    op.create_table('game_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Владелец сессии'),
    sa.Column('game_over', sa.Boolean(), nullable=False, comment='Игра завершена'),
    sa.Column('current_cycle', sa.Integer(), nullable=False, comment='Игровой день (1..365)'),
    sa.Column('current_time', sa.String(length=5), nullable=False, comment='Игровое время HH:MM'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False, comment='Игровая сессия'),
    sa.Column('role', sa.Text(), nullable=False, comment="'user', 'assistant', 'system', 'npc'"),
    sa.Column('content', sa.Text(), nullable=False, comment='Текст сообщения'),
    sa.Column('cycle', sa.Integer(), nullable=False, comment='Игровой цикл'),
    sa.Column('tokens_used', sa.Integer(), nullable=False, comment='Потрачено токенов'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('floors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False, comment='Игровая сессия'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='Название ("этаж 345", "партийный", "тёмный")'),
    sa.Column('description', sa.Text(), nullable=False, comment='Описание этажа'),
    sa.Column('is_inhabited', sa.Boolean(), nullable=False, comment='Обитаем ли этаж'),
    sa.Column('danger_level', sa.Float(), nullable=False, comment='Уровень опасности 0.0 - 1.0'),
    sa.Column('is_contaminated', sa.Boolean(), nullable=False, comment='Загрязнён Самосбором'),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False, comment='Игровая сессия'),
    sa.Column('name', sa.Text(), nullable=False, comment='Название ("Комната 312", "Коридор секции Б")'),
    sa.Column('description', sa.Text(), nullable=False, comment='Текстовое описание'),
    sa.Column('floor_id', sa.Integer(), nullable=False, comment='Этаж'),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location_connections',
    sa.Column('from_location_id', sa.Integer(), nullable=False),
    sa.Column('to_location_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False, comment='Описание перехода'),
    sa.Column('transition_type', sa.Text(), nullable=False, comment='Тип: door, stairs, elevator, vent, hatch, tunnel'),
    sa.Column('is_locked', sa.Boolean(), nullable=False, comment='Заперт ли переход'),
    sa.ForeignKeyConstraint(['from_location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('from_location_id', 'to_location_id')
    )
    op.create_table('persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False, comment='Игровая сессия'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='Имя'),
    sa.Column('bio', sa.Text(), nullable=False, comment='Биография'),
    sa.Column('personality', sa.Text(), nullable=False, comment='Характер'),
    sa.Column('appearance', sa.Text(), nullable=False, comment='Внешность'),
    sa.Column('habits', sa.Text(), nullable=False, comment='Привычки'),
    sa.Column('current_location_id', sa.Integer(), nullable=True, comment='Текущая локация'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['current_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interaction_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False, comment='Игровая сессия'),
    sa.Column('person_id', sa.Integer(), nullable=False, comment='Кто взаимодействовал'),
    sa.Column('target_person_id', sa.Integer(), nullable=False, comment='С кем взаимодействовал'),
    sa.Column('event', sa.Text(), nullable=False, comment='Текстовое описание события'),
    sa.Column('cycle', sa.Integer(), nullable=False, comment='Игровой цикл'),
    sa.Column('time', sa.Text(), nullable=False, comment='Игровое время HH:MM'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False, comment='Игровая сессия'),
    sa.Column('name', sa.Text(), nullable=False, comment='Название'),
    sa.Column('description', sa.Text(), nullable=False, comment='Описание'),
    sa.Column('owner_id', sa.Integer(), nullable=True, comment='У кого сейчас (если у персонажа)'),
    sa.Column('location_id', sa.Integer(), nullable=True, comment='Где лежит (если не у персонажа)'),
    sa.Column('is_equipped', sa.Boolean(), nullable=False, comment='Экипирован ли'),
    sa.Column('item_type', sa.Text(), nullable=False, comment='Тип: weapon, armour, food, tool, medical, document, key, misc'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location_visit_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False, comment='Игровая сессия'),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('visit_reason', sa.Text(), nullable=False, comment='Причина и обстоятельства'),
    sa.Column('cycle', sa.Integer(), nullable=False),
    sa.Column('time', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('npcs',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False, comment='Игровая сессия'),
    sa.Column('faction', sa.String(length=64), nullable=True, comment='Фракция'),
    sa.Column('danger_level', sa.Float(), nullable=False, comment='0.0 - 1.0'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('person_id')
    )
    op.create_table('players',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False, comment='Игровая сессия'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('person_id')
    )
    op.create_table('social_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False, comment='Игровая сессия'),
    sa.Column('from_person_id', sa.Integer(), nullable=False),
    sa.Column('to_person_id', sa.Integer(), nullable=False),
    sa.Column('affinity', sa.Float(), nullable=False, comment='Отношение: -1.0 (ненависть) .. 1.0 (обожание), 0 = нейтрально'),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False, comment='Игровая сессия'),
    sa.Column('title', sa.Text(), nullable=False, comment='Название ("Найти воду", "Починить фильтр")'),
    sa.Column('description', sa.Text(), nullable=False, comment='Подробное описание'),
    sa.Column('assignee_id', sa.Integer(), nullable=False, comment='Кому назначена'),
    sa.Column('location_id', sa.Integer(), nullable=True, comment='Где выполнять'),
    sa.Column('location_hint', sa.Text(), nullable=True, comment='"Где-то на 3-м этаже"'),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('reward', sa.Text(), nullable=True, comment='Награда ("Пайка на неделю")'),
    sa.Column('summary', sa.Text(), nullable=True, comment='Саммари прогресса'),
    sa.ForeignKeyConstraint(['assignee_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('social_relations')
    op.drop_table('players')
    op.drop_table('npcs')
    op.drop_table('location_visit_history')
    op.drop_table('items')
    op.drop_table('interaction_history')
    op.drop_table('persons')
    op.drop_table('location_connections')
    op.drop_table('locations')
    op.drop_table('floors')
    op.drop_table('conversations')
    op.drop_table('game_sessions')
    op.drop_table('users')
    op.drop_index('idx_document_chunks_source', table_name='document_chunks')
    op.drop_index('idx_document_chunks_embedding', table_name='document_chunks', postgresql_using='hnsw')
    op.drop_table('document_chunks')
    # ### end Alembic commands ###
